services:
  virtual_client:
    build: ./VechicleDigitalTwin
    container_name: VechicleDigitalTwin_container
    environment:
      - MQTT_SERVER_ADDRESS=34.155.54.234
      - MQTT_SERVER_PORT=1883
      - PYTHONUNBUFFERED=1
    volumes:
      - ./VechicleDigitalTwin/code:/etc/usr/src/code
    restart: unless-stopped

