services:
  mosquitto:
    build: ./mosquitto
    container_name: mosquitto_container
    ports:
      - "1883:1883"
    volumes:
      - "./code:/etc/mosquitto"
    restart: unless-stopped

  message_router:
    build: ./message_router
    container_name: message_router
    environment:
      - MQTT_SERVER_ADDRESS=mosquitto
      - MQTT_SERVER_PORT=1883
      - PYTHONUNBUFFERED=1
    volumes:
      - "./message_router/code:/usr/src/app"
    depends_on:
      - mosquitto
    restart: unless-stopped
